vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       products:
           uri_prefix: /pictures
           upload_destination: '%kernel.project_dir%/assets/pictures'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
